export const HotelJSON = [
    {
      hotel_id: 1,
      chain_id: 421,
      chain_name: "Samed Resorts Group",
      brand_id: 0,
      brand_name: "",
      hotel_name: "Sai Kaew Beach Resort",
      hotel_formerly_name: "",
      hotel_translated_name: "Sai Kaew Beach Resort",
      addressline1: "8/1 Moo 4 Tumbon Phe Muang",
      addressline2: "",
      zipcode: "21160",
      city: "Chiang Mai",
      state: "Northern Thailand",
      country: "Thailand",
      countryisocode: "TH",
      star_rating: 4,
      longitude: 101.466979,
      latitude: 12.568135,
      url: "https://www.agoda.com/partners/partnersearch.aspx?hid=1",
      checkin: "2:00 PM",
      checkout: "11:30 AM",
      numberrooms: 160,
      numberfloors: null,
      yearopened: 2000,
      yearrenovated: 2018,
      photo1:
        "http://pix2.agoda.net/hotelimages/1/-1/0ff4876f93688b8adcbed487b5a2175d.jpg?s=312x",
      photo2:
        "http://pix1.agoda.net/hotelimages/1/-1/d821f80943f96ebda33f5a019fa94df4.jpg?s=312x",
      photo3:
        "http://pix4.agoda.net/hotelimages/1/-1/59241704e99027895aa6293d734c9fb1.jpg?s=312x",
      photo4:
        "http://pix5.agoda.net/hotelimages/1/-1/fce5d70fac02fcb7aa25f31dd25850a8.jpg?s=312x",
      photo5:
        "http://pix1.agoda.net/hotelimages/1/-1/7952a908de348304417552246f9039de.jpg?s=312x",
      overview:
        "The 4-star Sai Kaew Beach Resort offers comfort and convenience whether you're on business or holiday in Koh Samet. The property features a wide range of facilities to make your stay a pleasant experience. Free Wi-Fi in all rooms, daily housekeeping, gift/souvenir shop, 24-hour front desk, Wi-Fi in public areas are just some of the facilities on offer. Some of the well-appointed guestrooms feature slippers, separate living room, television LCD/plasma screen, mirror, internet access – wireless. Take a break from a long day and make use of fitness center, sauna, outdoor pool, spa, massage. No matter what your reasons are for visiting Koh Samet, Sai Kaew Beach Resort will make you feel instantly at home.",
      rates_from: 166,
      continent_id: 2,
      continent_name: "Asia",
      city_id: 17222,
      country_id: 106,
      number_of_reviews: 3439,
      rating_average: 8.2,
      rates_currency: "USD",
    },
    {
      hotel_id: 6,
      chain_id: 0,
      chain_name: "No chain",
      brand_id: 0,
      brand_name: "",
      hotel_name: "Marine Hotel",
      hotel_formerly_name: "",
      hotel_translated_name: "Marine Hotel",
      addressline1: "Sutton Cross",
      addressline2: "",
      zipcode: "D13",
      city: "Bangkok",
      state: "Central Thailand",
      country: "Thailand",
      countryisocode: "IE",
      star_rating: 3,
      longitude: -6.11034,
      latitude: 53.38884,
      url: "https://www.agoda.com/partners/partnersearch.aspx?hid=6",
      checkin: "3:00 PM",
      checkout: "12:00 PM",
      numberrooms: null,
      numberfloors: null,
      yearopened: null,
      yearrenovated: null,
      photo1:
        "http://pix4.agoda.net/hotelimages/6/6/6_1112201742005261861.jpg?s=312x",
      photo2:
        "http://pix2.agoda.net/hotelimages/6/6/6_1201211018006071850.jpg?s=312x",
      photo3:
        "http://pix5.agoda.net/hotelimages/6/6/6_0905131455001101926.jpg?s=312x",
      photo4:
        "http://pix1.agoda.net/hotelimages/6/6/6_0905131455001101927.jpg?s=312x",
      photo5:
        "http://pix4.agoda.net/hotelimages/6/6/6_0905131455001101930.jpg?s=312x",
      overview:
        "Marine Hotel is perfectly located for both business and leisure guests in Dublin. The hotel offers guests a range of services and amenities designed to provide comfort and convenience. Free Wi-Fi in all rooms, 24-hour front desk, luggage storage, car park, room service are just some of the facilities on offer. Comfortable guestrooms ensure a good night's sleep with some rooms featuring facilities such as heating, telephone, television, satellite/cable TV, shower. Entertain the hotel's recreational facilities, including sauna, golf course (within 3 km), indoor pool, garden. No matter what your reasons are for visiting Dublin, Marine Hotel will make you feel instantly at home.",
      rates_from: 144,
      continent_id: 4,
      continent_name: "Europe",
      city_id: 1131,
      country_id: 188,
      number_of_reviews: 12,
      rating_average: 7.4,
      rates_currency: "USD",
    },

    {
      hotel_id: 1,
      chain_id: 421,
      chain_name: "Samed Resorts Group",
      brand_id: 0,
      brand_name: "",
      hotel_name: "Sai Kaew Beach Resort",
      hotel_formerly_name: "",
      hotel_translated_name: "Sai Kaew Beach Resort",
      addressline1: "8/1 Moo 4 Tumbon Phe Muang",
      addressline2: "",
      zipcode: "21160",
      city: "Chiang Rai",
      state: "Northern Thailand",
      country: "Thailand",
      countryisocode: "TH",
      star_rating: 4,
      longitude: 101.466979,
      latitude: 12.568135,
      url: "https://www.agoda.com/partners/partnersearch.aspx?hid=1",
      checkin: "2:00 PM",
      checkout: "11:30 AM",
      numberrooms: 160,
      numberfloors: null,
      yearopened: 2000,
      yearrenovated: 2018,
      photo1:
        "http://pix2.agoda.net/hotelimages/1/-1/0ff4876f93688b8adcbed487b5a2175d.jpg?s=312x",
      photo2:
        "http://pix1.agoda.net/hotelimages/1/-1/d821f80943f96ebda33f5a019fa94df4.jpg?s=312x",
      photo3:
        "http://pix4.agoda.net/hotelimages/1/-1/59241704e99027895aa6293d734c9fb1.jpg?s=312x",
      photo4:
        "http://pix5.agoda.net/hotelimages/1/-1/fce5d70fac02fcb7aa25f31dd25850a8.jpg?s=312x",
      photo5:
        "http://pix1.agoda.net/hotelimages/1/-1/7952a908de348304417552246f9039de.jpg?s=312x",
      overview:
        "The 4-star Sai Kaew Beach Resort offers comfort and convenience whether you're on business or holiday in Koh Samet. The property features a wide range of facilities to make your stay a pleasant experience. Free Wi-Fi in all rooms, daily housekeeping, gift/souvenir shop, 24-hour front desk, Wi-Fi in public areas are just some of the facilities on offer. Some of the well-appointed guestrooms feature slippers, separate living room, television LCD/plasma screen, mirror, internet access – wireless. Take a break from a long day and make use of fitness center, sauna, outdoor pool, spa, massage. No matter what your reasons are for visiting Koh Samet, Sai Kaew Beach Resort will make you feel instantly at home.",
      rates_from: 166,
      continent_id: 2,
      continent_name: "Asia",
      city_id: 17222,
      country_id: 106,
      number_of_reviews: 3439,
      rating_average: 8.2,
      rates_currency: "USD",
    },
    {
      hotel_id: 6,
      chain_id: 0,
      chain_name: "No chain",
      brand_id: 0,
      brand_name: "",
      hotel_name: "Marine Hotel",
      hotel_formerly_name: "",
      hotel_translated_name: "Marine Hotel",
      addressline1: "Sutton Cross",
      addressline2: "",
      zipcode: "D13",
      city: "Phuket",
      state: "Central Thailand",
      country: "Thailand",
      countryisocode: "IE",
      star_rating: 3,
      longitude: -6.11034,
      latitude: 53.38884,
      url: "https://www.agoda.com/partners/partnersearch.aspx?hid=6",
      checkin: "3:00 PM",
      checkout: "12:00 PM",
      numberrooms: null,
      numberfloors: null,
      yearopened: null,
      yearrenovated: null,
      photo1:
        "http://pix4.agoda.net/hotelimages/6/6/6_1112201742005261861.jpg?s=312x",
      photo2:
        "http://pix2.agoda.net/hotelimages/6/6/6_1201211018006071850.jpg?s=312x",
      photo3:
        "http://pix5.agoda.net/hotelimages/6/6/6_0905131455001101926.jpg?s=312x",
      photo4:
        "http://pix1.agoda.net/hotelimages/6/6/6_0905131455001101927.jpg?s=312x",
      photo5:
        "http://pix4.agoda.net/hotelimages/6/6/6_0905131455001101930.jpg?s=312x",
      overview:
        "Marine Hotel is perfectly located for both business and leisure guests in Dublin. The hotel offers guests a range of services and amenities designed to provide comfort and convenience. Free Wi-Fi in all rooms, 24-hour front desk, luggage storage, car park, room service are just some of the facilities on offer. Comfortable guestrooms ensure a good night's sleep with some rooms featuring facilities such as heating, telephone, television, satellite/cable TV, shower. Entertain the hotel's recreational facilities, including sauna, golf course (within 3 km), indoor pool, garden. No matter what your reasons are for visiting Dublin, Marine Hotel will make you feel instantly at home.",
      rates_from: 144,
      continent_id: 4,
      continent_name: "Europe",
      city_id: 1131,
      country_id: 188,
      number_of_reviews: 12,
      rating_average: 7.4,
      rates_currency: "USD",
    },
    {
      hotel_id: 10,
      chain_id: 29,
      chain_name: "Melia Hotels International",
      brand_id: 128,
      brand_name: "Tryp",
      hotel_name: "TRYP Malaga Alameda Hotel",
      hotel_formerly_name: "",
      hotel_translated_name: "TRYP Malaga Alameda Hotel",
      addressline1: "Avenida de la Aurora CC.Larios Centro S/N",
      addressline2: "",
      zipcode: "29002",
      city: "Kanchanaburi",
      state: "Western Thailand",
      discount:10,
      country: "Thailand",
      countryisocode: "ES",
      star_rating: 4,
      longitude: -4.432833,
      latitude: 36.716057,
      url: "https://www.agoda.com/partners/partnersearch.aspx?hid=10",
      checkin: "1:00 PM",
      checkout: "12:00 PM",
      numberrooms: 132,
      numberfloors: null,
      yearopened: null,
      yearrenovated: null,
      photo1:
        "http://pix1.agoda.net/hotelimages/4890100/0/bbdf04328f691e68828c8f49075ace5e.jpg?s=312x",
      photo2:
        "http://pix2.agoda.net/hotelimages/10/10/10_14041821020019130452.jpg?s=312x",
      photo3:
        "http://pix5.agoda.net/hotelimages/10/10/10_13051721000012487062.jpg?s=312x",
      photo4:
        "http://pix5.agoda.net/hotelimages/10/10/10_13051721000012487063.jpg?s=312x",
      photo5:
        "http://pix2.agoda.net/hotelimages/10/10/10_13051721010012487064.jpg?s=312x",
      overview:
        "TRYP Málaga Alameda Hotel is perfectly located for both business and leisure guests in Malaga. The hotel has everything you need for a comfortable stay. To be found at the hotel are 24-hour room service, free Wi-Fi in all rooms, 24-hour front desk, facilities for disabled guests, Wi-Fi in public areas. Each guestroom is elegantly furnished and equipped with handy amenities. The hotel's peaceful atmosphere extends to its recreational facilities which include fitness center, sauna. TRYP Málaga Alameda Hotel combines warm hospitality with a lovely ambiance to make your stay in Malaga unforgettable.",
      rates_from: 83,
      continent_id: 4,
      continent_name: "Europe",
      city_id: 12521,
      country_id: 167,
      number_of_reviews: 21,
      rating_average: 7.5,
      rates_currency: "USD",
    },
    {
      hotel_id: 13,
      chain_id: 227,
      chain_name: "NH Hotels",
      brand_id: 451,
      brand_name: "NH Hotels",
      hotel_name: "NH Iquique Hotel",
      hotel_formerly_name: "Radisson Hotel Iquique",
      hotel_translated_name: "NH Iquique Hotel",
      addressline1: "Av Costanera 3939",
      addressline2: "",
      zipcode: "1111500",
      city: "Krabi",
      state: "Western Thailand",
      country: "Thailand",
      countryisocode: "CL",
      star_rating: 4,
      longitude: -70.129991,
      latitude: -20.269986,
      url: "https://www.agoda.com/partners/partnersearch.aspx?hid=13",
      checkin: "3:00 PM",
      checkout: "12:00 PM",
      discount:10,
      numberrooms: null,
      numberfloors: null,
      yearopened: null,
      yearrenovated: null,
      photo1:
        "http://pix3.agoda.net/hotelimages/13/0/5f8b6d43a6a287d37bfe1626ab22b0b1.jpg?s=312x",
      photo2:
        "http://pix4.agoda.net/hotelimages/13/13/13_15072020190032641184.jpg?s=312x",
      photo3:
        "http://pix5.agoda.net/hotelimages/13/13/13_15072020200032641185.jpg?s=312x",
      photo4:
        "http://pix1.agoda.net/hotelimages/13/13/13_15072020200032641186.jpg?s=312x",
      photo5:
        "http://pix2.agoda.net/hotelimages/13/0/ff8100c85955522a0289e5c71329a17a.jpg?s=312x",
      overview:
        "NH Iquique Hotel is perfectly located for both business and leisure guests in Iquique. The hotel offers guests a range of services and amenities designed to provide comfort and convenience. All the necessary facilities, including 24-hour front desk, facilities for disabled guests, Wi-Fi in public areas, car park, room service, are at hand. Guestrooms are designed to provide an optimal level of comfort with welcoming decor and some offering convenient amenities like television LCD/plasma screen, separate living room, air conditioning, heating, wake-up service. To enhance guests' stay, the hotel offers recreational facilities such as fitness center, outdoor pool. A welcoming atmosphere and excellent service are what you can expect during your stay at NH Iquique Hotel.",
      rates_from: 66,
      continent_id: 8,
      continent_name: "South America",
      city_id: 3527,
      country_id: 69,
      number_of_reviews: 5,
      rating_average: 5.9,
      rates_currency: "USD",
    },
    {
      hotel_id: 15,
      chain_id: 21,
      chain_name: "Marriott",
      brand_id: 3821,
      brand_name: "Sheraton",
      hotel_name: "Sheraton Grand Hotel & Spa, Edinburgh",
      hotel_formerly_name: "Sheraton Grand Hotel and Spa Edinburgh",
      hotel_translated_name: "Sheraton Grand Hotel & Spa, Edinburgh",
      addressline1: "1 Festival Square",
      addressline2: "",
      zipcode: "EH39SR",
      city: "Lampang",
      state: "Western Thailand",
      country: "Thailand",
      countryisocode: "GB",
      star_rating: 5,
      longitude: -3.207612,
      latitude: 55.947063,
      url: "https://www.agoda.com/partners/partnersearch.aspx?hid=15",
      checkin: "3:00 PM",
      checkout: "12:00 PM",
      numberrooms: 269,
      numberfloors: null,
      yearopened: null,
      yearrenovated: null,
      photo1:
        "http://pix3.agoda.net/hotelimages/15/0/59a863c3a6e93b759faf2beea910d516.jpg?s=312x",
      photo2:
        "http://pix5.agoda.net/hotelimages/15/15/15_13072409510013984463.jpg?s=312x",
      photo3:
        "http://pix2.agoda.net/hotelimages/15/15/15_17091312040056285473.jpg?s=312x",
      photo4:
        "http://pix4.agoda.net/hotelimages/15/15/15_17091312040056285476.jpg?s=312x",
      photo5:
        "http://pix5.agoda.net/hotelimages/15/15/15_17091312040056285477.jpg?s=312x",
      overview:
        "Sheraton Grand Hotel & Spa, Edinburgh is perfectly located for both business and leisure guests in Edinburgh. The hotel has everything you need for a comfortable stay. 24-hour room service, free Wi-Fi in all rooms, 24-hour security, daily housekeeping, fireplace are there for guest's enjoyment. Each guestroom is elegantly furnished and equipped with handy amenities. The hotel offers various recreational opportunities. Sheraton Grand Hotel & Spa, Edinburgh is an excellent choice from which to explore Edinburgh or to simply relax and rejuvenate.",
      rates_from: 185,
      continent_id: 4,
      continent_name: "Europe",
      city_id: 18924,
      country_id: 107,
      number_of_reviews: 35,
      discount:10,
      rating_average: 8.8,
      rates_currency: "USD",
    },
    {
      hotel_id: 16,
      chain_id: 496,
      chain_name: "HK CTS Hotels",
      brand_id: 4382,
      brand_name: "Kew Green",
      hotel_name: "Kew Green Hotel Wanchai Hong Kong",
      hotel_formerly_name: "Metropark Hotel Wanchai Hong Kong",
      hotel_translated_name: "Kew Green Hotel Wanchai Hong Kong",
      addressline1: "41-49 Hennessy Road",
      addressline2: "",
      zipcode: "",
      city: "Sukhothai",
      state: "Lower northern Thailand",
      country: "Thailand",
      countryisocode: "HK",
      star_rating: 4,
      longitude: 114.170576,
      latitude: 22.277779,
      url: "https://www.agoda.com/partners/partnersearch.aspx?hid=16",
      checkin: "2:00 PM",
      checkout: "12:00 PM",
      numberrooms: 173,
      numberfloors: 18,
      yearopened: null,
      yearrenovated: 2007,
      photo1:
        "http://pix3.agoda.net/hotelimages/16/16/16_17072912020054755824.jpg?s=312x",
      photo2:
        "http://pix5.agoda.net/hotelimages/16/16/16_15121810140038604789.jpg?s=312x",
      photo3:
        "http://pix4.agoda.net/hotelimages/16/16/16_13022217540010401585.jpg?s=312x",
      photo4:
        "http://pix5.agoda.net/hotelimages/16/16/16_13102910330017213949.jpg?s=312x",
      photo5:
        "http://pix5.agoda.net/hotelimages/16/16/16_15121810140038604781.jpg?s=312x",
      overview:
        "The 4-star Kew Green Hotel Wanchai Hong Kong offers comfort and convenience whether you're on business or holiday in Hong Kong. Both business travelers and tourists can enjoy the hotel's facilities and services. Service-minded staff will welcome and guide you at the Kew Green Hotel Wanchai Hong Kong. Each guestroom is elegantly furnished and equipped with handy amenities. The hotel's peaceful atmosphere extends to its recreational facilities which include fitness center. Friendly staff, great facilities and close proximity to all that Hong Kong has to offer are three great reasons you should stay at Kew Green Hotel Wanchai Hong Kong.",
      rates_from: 428,
      continent_id: 2,
      continent_name: "Asia",
      city_id: 16808,
      country_id: 132,
      number_of_reviews: 4206,
      rating_average: 8.1,
      rates_currency: "USD",
    },
    {
      hotel_id: 17,
      chain_id: 0,
      chain_name: "No chain",
      brand_id: 0,
      brand_name: "",
      hotel_name: "Hotel Dann Carlton Medellin",
      hotel_formerly_name: "",
      hotel_translated_name: "Hotel Dann Carlton Medellin",
      addressline1: "Cra 43A No. 7-50",
      addressline2: "",
      zipcode: "50001",
      city: "Ayutthaya",
      state: "Lower northern Thailand",
      country: "Thailand",
      countryisocode: "CO",
      discount:10,
      star_rating: 5,
      longitude: -75.571053,
      latitude: 6.20724,
      url: "https://www.agoda.com/partners/partnersearch.aspx?hid=17",
      checkin: "3:00 PM",
      checkout: "1:00 PM",
      numberrooms: null,
      numberfloors: null,
      yearopened: null,
      yearrenovated: null,
      photo1:
        "http://pix5.agoda.net/hotelimages/17/17/17_16051513410042341853.jpg?s=312x",
      photo2:
        "https://q-xx.bstatic.com/xdata/images/hotel/max500/106650431.jpg?k=5a97e1aef0eef91b1a38caa55387f33ddc2c7e7990291682f4b2928f5b9d7e48&o=",
      photo3:
        "http://pix3.agoda.net/hotelimages/17/17/17_0912182150001859572.jpg?s=312x",
      photo4:
        "http://pix3.agoda.net/hotelimages/17/17/17_0912182150001859573.jpg?s=312x",
      photo5:
        "http://pix5.agoda.net/hotelimages/17/17/17_0912182150001859577.jpg?s=312x",
      overview:
        "The 5-star Hotel Dann Carlton Medellín offers comfort and convenience whether you're on business or holiday in Medellin. Both business travelers and tourists can enjoy the hotel's facilities and services. Facilities like 24-hour front desk, facilities for disabled guests, luggage storage, room service, airport transfer are readily available for you to enjoy. Some of the well-appointed guestrooms feature air conditioning, wake-up service, desk, mini bar, alarm clock. Recuperate from a full day of sightseeing in the comfort of your room or take advantage of the hotel's recreational facilities, including fitness center, outdoor pool, spa, massage, steamroom. Friendly staff, great facilities and close proximity to all that Medellin has to offer are three great reasons you should stay at Hotel Dann Carlton Medellín.",
      rates_from: 78,
      continent_id: 8,
      continent_name: "South America",
      city_id: 10309,
      country_id: 10,
      number_of_reviews: 15,
      rating_average: 8.1,
      rates_currency: "USD",
    },
    {
      hotel_id: 18,
      chain_id: 0,
      chain_name: "No chain",
      brand_id: 0,
      brand_name: "",
      hotel_name: "Grand Coloane Resort",
      hotel_formerly_name: "Grand Coloane Beach Resort",
      hotel_translated_name: "Grand Coloane Resort",
      addressline1: "1918 Estrada de Hac Sa",
      addressline2: "",
      zipcode: "",
      city: "Hua Hin",
      state: "Lower northern Thailand",
      country: "Thailand",
      countryisocode: "MO",
      star_rating: 5,
      longitude: 113.576574,
      latitude: 22.125391,
      url: "https://www.agoda.com/partners/partnersearch.aspx?hid=18",
      checkin: "3:00 PM",
      checkout: "12:00 PM",
      numberrooms: 208,
      numberfloors: 8,
      yearopened: 1993,
      yearrenovated: 2014,
      photo1:
        "http://pix4.agoda.net/hotelimages/18/-1/91c5a3c5d5cc7189b0099fab9a2fbb64.jpg?s=312x",
      photo2:
        "http://pix1.agoda.net/hotelimages/18/18/18_15060216180028256873.jpg?s=312x",
      photo3:
        "http://pix4.agoda.net/hotelimages/18/18/18_121122143051695.jpg?s=312x",
      photo4:
        "http://pix2.agoda.net/hotelimages/18/18/18_121122143052132.jpg?s=312x",
      photo5:
        "http://pix2.agoda.net/hotelimages/18/18/18_121122143052678.jpg?s=312x",
      overview:
        "Grand Coloane Resort is conveniently located in the popular Coloane area. The hotel offers a wide range of amenities and perks to ensure you have a great time. Take advantage of the hotel's 24-hour room service, daily housekeeping, free Wi-Fi in all rooms, taxi service, 24-hour security. Designed for comfort, selected guestrooms offer television LCD/plasma screen, additional toilet, bathroom phone, carpeting, clothes rack to ensure a restful night. Entertain the hotel's recreational facilities, including hot tub, fitness center, sauna, golf course (on site), outdoor pool. Grand Coloane Resort is an excellent choice from which to explore Macau or to simply relax and rejuvenate.",
      rates_from: 125,
      continent_id: 2,
      continent_name: "Asia",
      city_id: 21397,
      country_id: 169,
      number_of_reviews: 3657,
      rating_average: 8,
      rates_currency: "USD",
    },
    {
      hotel_id: 25,
      chain_id: 2688,
      chain_name: "Skycity",
      brand_id: 3990,
      brand_name: "Skycity",
      hotel_name: "SKYCITY Hotel",
      hotel_formerly_name: "",
      hotel_translated_name: "SKYCITY Hotel",
      addressline1: "Corner Victoria & Federal Streets",
      addressline2: "",
      zipcode: "1010",
      city: "Pattaya",
      state: "Eastern Thailand",
      country: "Thailand",
      countryisocode: "NZ",
      star_rating: 4.5,
      longitude: 174.761966,
      latitude: -36.848387,
      url: "https://www.agoda.com/partners/partnersearch.aspx?hid=25",
      checkin: "3:00 PM",
      checkout: "11:00 AM",
      numberrooms: 323,
      numberfloors: 8,
      yearopened: 1996,
      yearrenovated: null,
      photo1:
        "http://pix3.agoda.net/hotelimages/25/-1/8dad037385fd554a85e013f931a8a1d5.jpg?s=312x",
      photo2:
        "http://pix2.agoda.net/hotelimages/25/25/25_15062308450030331242.jpg?s=312x",
      photo3:
        "http://pix5.agoda.net/hotelimages/25/25/25_15062308460030331423.jpg?s=312x",
      photo4:
        "http://pix2.agoda.net/hotelimages/25/25/25_15062308460030331424.jpg?s=312x",
      photo5:
        "http://pix2.agoda.net/hotelimages/25/25/25_15062308460030331425.jpg?s=312x",
      overview:
        "Skycity Hotel is perfectly located for both business and leisure guests in Auckland. Offering a variety of facilities and services, the hotel provides all you need for a good night's sleep. To be found at the hotel are 24-hour room service, free Wi-Fi in all rooms, wheelchair accessible, casino, 24-hour front desk. Guestrooms are fitted with all the amenities you need for a good night's sleep. In some of the rooms, guests can find television LCD/plasma screen, carpeting, complimentary instant coffee, complimentary tea, mirror. The hotel's peaceful atmosphere extends to its recreational facilities which include fitness center, spa, massage. A welcoming atmosphere and excellent service are what you can expect during your stay at Skycity Hotel.",
      rates_from: 117,
      continent_id: 7,
      continent_name: "Pacific Ocean and Australia",
      city_id: 3750,
      country_id: 25,
      number_of_reviews: 1425,
      discount:10,
      rating_average: 8.5,
      rates_currency: "USD",
    },
    {
      hotel_id: 33,
      chain_id: 3,
      chain_name: "Accor Hotels",
      brand_id: 36,
      brand_name: "Pullman",
      hotel_name: "Pullman Bordeaux Lac",
      hotel_formerly_name: "Sofitel Bordeaux Aquitania Hotel",
      hotel_translated_name: "Pullman Bordeaux Lac",
      addressline1: "Avenue Jean Gabriel Domergue",
      addressline2: "",
      zipcode: "33300",
      city: "Hat Yai,",
      state: "Eastern Thailand",
      country: "Thailand",
      countryisocode: "FR",
      star_rating: 4,
      longitude: -0.565954,
      latitude: 44.889622,
      url: "https://www.agoda.com/partners/partnersearch.aspx?hid=33",
      checkin: "2:00 PM",
      checkout: "12:00 PM",
      numberrooms: null,
      numberfloors: null,
      yearopened: null,
      yearrenovated: null,
      photo1:
        "http://pix3.agoda.net/hotelimages/6584938/0/dc16bcf0fcfe7d2d5110462ebed1705b.jpg?s=312x",
      photo2:
        "http://pix3.agoda.net/hotelimages/33/33/33_15022714410025654631.jpg?s=312x",
      photo3:
        "http://pix4.agoda.net/hotelimages/33/33/33_17080709240054945185.jpg?s=312x",
      photo4:
        "http://pix5.agoda.net/hotelimages/33/33/33_17080709240054945186.jpg?s=312x",
      photo5:
        "http://pix3.agoda.net/hotelimages/33/33/33_17080709240054945187.jpg?s=312x",
      overview:
        "Located in Le Lac, Pullman Bordeaux Lac is a perfect starting point from which to explore Bordeaux. Offering a variety of facilities and services, the hotel provides all you need for a good night's sleep. Casino, 24-hour front desk, facilities for disabled guests, luggage storage, Wi-Fi in public areas are just some of the facilities on offer. Each guestroom is elegantly furnished and equipped with handy amenities. To enhance guests' stay, the hotel offers recreational facilities such as fitness center, golf course (within 3 km), outdoor pool, massage, solarium. Pullman Bordeaux Lac is an excellent choice from which to explore Bordeaux or to simply relax and rejuvenate.",
      rates_from: 136,
      continent_id: 4,
      continent_name: "Europe",
      city_id: 12838,
      country_id: 153,
      number_of_reviews: 21,
      rating_average: 8.2,
      rates_currency: "USD",
    },
    {
      hotel_id: 34,
      chain_id: 0,
      chain_name: "No chain",
      brand_id: 0,
      brand_name: "",
      hotel_name: "Hotel Conde Luna",
      hotel_formerly_name: "",
      hotel_translated_name: "Hotel Conde Luna",
      addressline1: "Avenida Independencia, 7",
      addressline2: "",
      zipcode: "24003",
      city: "Surat Thani",
      state: "Southern Thailand,",
      country: "Thailand",
      countryisocode: "ES",
      star_rating: 4,
      longitude: -5.57119,
      latitude: 42.596451,
      url: "https://www.agoda.com/partners/partnersearch.aspx?hid=34",
      checkin: "2:00 PM",
      checkout: "12:00 PM",
      numberrooms: null,
      numberfloors: null,
      yearopened: null,
      yearrenovated: null,
      photo1:
        "http://pix3.agoda.net/hotelimages/34/34/34_08091300010079.jpg?s=312x",
      photo2:
        "http://pix5.agoda.net/hotelimages/34/34/34_1001231702002566194.jpg?s=312x",
      photo3:
        "http://pix5.agoda.net/hotelimages/34/34/34_0912031414001753274.jpg?s=312x",
      photo4:
        "http://pix5.agoda.net/hotelimages/34/34/34_0912031414001753275.jpg?s=312x",
      photo5:
        "http://pix5.agoda.net/hotelimages/34/34/34_0912190835001951320.jpg?s=312x",
      overview:
        "Stop at Hotel Conde Luna to discover the wonders of Leon. Both business travelers and tourists can enjoy the hotel's facilities and services. 24-hour front desk, luggage storage, room service, meeting facilities, babysitting are on the list of things guests can enjoy. Some of the well-appointed guestrooms feature air conditioning, heating, wake-up service, desk, mini bar. Entertain the hotel's recreational facilities, including massage. No matter what your reasons are for visiting Leon, Hotel Conde Luna will make you feel instantly at home.",
      rates_from: 75,
      continent_id: 4,
      continent_name: "Europe",
      city_id: 7609,
      country_id: 167,
      number_of_reviews: 10,
      rating_average: 8.5,
      discount:10,
      rates_currency: "USD",
    },
    {
      hotel_id: 36,
      chain_id: 0,
      chain_name: "No chain",
      brand_id: 0,
      brand_name: "",
      hotel_name: "Park Suisse Hotel",
      hotel_formerly_name: "",
      hotel_translated_name: "Park Suisse Hotel",
      addressline1: "Via Favale 31",
      addressline2: "",
      zipcode: "16038",
      city: "Koh Samui",
      state: "Southern Thailand,",
      country: "Thailand",
      countryisocode: "IT",
      star_rating: 4,
      longitude: 9.211559,
      latitude: 44.330683,
      url: "https://www.agoda.com/partners/partnersearch.aspx?hid=36",
      checkin: "3:00 PM",
      checkout: "12:00 PM",
      numberrooms: 72,
      numberfloors: 6,
      yearopened: 1956,
      yearrenovated: 2019,
      photo1:
        "http://pix5.agoda.net/hotelimages/36/36/36_16060914140043329990.jpg?s=312x",
      photo2:
        "http://pix2.agoda.net/hotelimages/36/36/36_13121423570017903834.jpg?s=312x",
      photo3:
        "http://pix1.agoda.net/hotelimages/36/36/36_13121613040017908699.jpg?s=312x",
      photo4:
        "http://pix1.agoda.net/hotelimages/36/36/36_13121613040017908703.jpg?s=312x",
      photo5:
        "http://pix2.agoda.net/hotelimages/36/36/36_16060914140043329983.jpg?s=312x",
      overview:
        "Set in a prime location of Santa Margherita Ligure, Park Suisse Hotel puts everything the city has to offer just outside your doorstep. Featuring a complete list of amenities, guests will find their stay at the property a comfortable one. 24-hour room service, free Wi-Fi in all rooms, Wi-Fi in public areas, valet parking, car park are on the list of things guests can enjoy. Television LCD/plasma screen, linens, mirror, closet, internet access – wireless can be found in selected guestrooms. The hotel offers various recreational opportunities. Discover all Santa Margherita Ligure has to offer by making Park Suisse Hotel your base.",
      rates_from: 73,
      continent_id: 4,
      continent_name: "Europe",
      city_id: 76473,
      country_id: 205,
      number_of_reviews: 55,
      rating_average: 7.5,
      rates_currency: "USD",
    },
    {
      hotel_id: 37,
      chain_id: 0,
      chain_name: "No chain",
      brand_id: 0,
      brand_name: "",
      hotel_name: "Hotel Agua Escondida",
      hotel_formerly_name: "",
      hotel_translated_name: "Hotel Agua Escondida",
      addressline1: "Guillermo Spartling, 4 Centro ",
      addressline2: "",
      zipcode: "40200",
      city: "Nakhon Ratchasima",
      state: "Northern Thailand",
      country: "Thailand",
      countryisocode: "MX",
      star_rating: 4,
      longitude: -99.60556,
      latitude: 18.55731,
      url: "https://www.agoda.com/partners/partnersearch.aspx?hid=37",
      checkin: "3:00 PM",
      checkout: "12:00 PM",
      numberrooms: null,
      numberfloors: null,
      yearopened: null,
      yearrenovated: null,
      photo1:
        "http://pix4.agoda.net/hotelimages/37/37/37_08112415020080.jpg?s=312x",
      photo2:
        "http://pix2.agoda.net/hotelimages/37/37/37_13060408140012629582.jpg?s=312x",
      photo3:
        "http://pix5.agoda.net/hotelimages/37/37/37_080913000100175992.jpg?s=312x",
      photo4:
        "http://pix2.agoda.net/hotelimages/37/37/37_080913000100175994.jpg?s=312x",
      photo5:
        "http://pix4.agoda.net/hotelimages/37/37/37_080913000100175995.jpg?s=312x",
      overview:
        "Located in Taxco City Center, Hotel Agua Escondida is a perfect starting point from which to explore Taxco. The hotel offers guests a range of services and amenities designed to provide comfort and convenience. Service-minded staff will welcome and guide you at the Hotel Agua Escondida. Each guestroom is elegantly furnished and equipped with handy amenities. The hotel offers various recreational opportunities. Convenience and comfort makes Hotel Agua Escondida the perfect choice for your stay in Taxco.",
      rates_from: 45,
      continent_id: 6,
      continent_name: "North America",
      city_id: 708,
      country_id: 86,
      number_of_reviews: 6,
      rating_average: 8.9,
      rates_currency: "USD",
    },
    {
      hotel_id: 38,
      chain_id: 0,
      chain_name: "No chain",
      brand_id: 0,
      brand_name: "",
      hotel_name: "Hotel Caribe Cartagena",
      hotel_formerly_name: "",
      hotel_translated_name: "Hotel Caribe Cartagena",
      addressline1: "Carrera 1, 2-87, Bocagrande",
      addressline2: "",
      zipcode: "130001",
      city: "Nonthaburi",
      state: "Northern Thailand",
      country: "Thailand",
      countryisocode: "CO",
      star_rating: 5,
      longitude: -75.560768,
      latitude: 10.397937,
      url: "https://www.agoda.com/partners/partnersearch.aspx?hid=38",
      checkin: "3:00 PM",
      checkout: "1:00 PM",
      numberrooms: 363,
      numberfloors: 7,
      yearopened: 1941,
      yearrenovated: 2010,
      discount:10,
      photo1:
        "http://pix5.agoda.net/hotelimages/38/38/38_120516001857736.jpg?s=312x",
      photo2:
        "http://pix3.agoda.net/hotelimages/38/38/38_111102221618017.jpg?s=312x",
      photo3:
        "http://pix2.agoda.net/hotelimages/38/38/38_0912190005001879680.jpg?s=312x",
      photo4:
        "http://pix2.agoda.net/hotelimages/38/38/38_0912190005001879681.jpg?s=312x",
      photo5:
        "http://pix4.agoda.net/hotelimages/38/38/38_0912190005001879683.jpg?s=312x",
      overview:
        "The 5-star Hotel Caribe Cartagena offers comfort and convenience whether you're on business or holiday in Cartagena. The hotel offers a high standard of service and amenities to suit the individual needs of all travelers. To be found at the hotel are 24-hour room service, free Wi-Fi in all rooms, facilities for disabled guests, Wi-Fi in public areas, car park. Designed for comfort, selected guestrooms offer cleaning products, mirror, closet, separate living room, internet access – wireless to ensure a restful night. Take a break from a long day and make use of hot tub, fitness center, sauna, golf course (on site), outdoor pool. Discover all Cartagena has to offer by making Hotel Caribe Cartagena your base.",
      rates_from: 123,
      continent_id: 8,
      continent_name: "South America",
      city_id: 10838,
      country_id: 10,
      number_of_reviews: 57,
      rating_average: 8.4,
      rates_currency: "USD",
    },
    {
      hotel_id: 54,
      chain_id: 0,
      chain_name: "No chain",
      brand_id: 0,
      brand_name: "",
      hotel_name: "Haihua Hotel Hangzhou",
      hotel_formerly_name: "Ramada Plaza Hai Hua Hotel",
      hotel_translated_name: "Haihua Hotel Hangzhou",
      addressline1: "No. 298, Qing Chun Road",
      addressline2: "",
      zipcode: "310006",
      city: "Samut",
      state: "Central Thailand",
      country: "Thailand",
      countryisocode: "CN",
      star_rating: 4,
      longitude: 120.160697,
      latitude: 30.258862,
      url: "https://www.agoda.com/partners/partnersearch.aspx?hid=54",
      checkin: "2:00 PM",
      checkout: "12:00 PM",
      numberrooms: 245,
      numberfloors: 8,
      yearopened: 1997,
      yearrenovated: 2010,
      photo1:
        "http://pix4.agoda.net/hotelimages/5081613/0/c4e6fab98811d18cf2d8068e517ccb62.jpg?s=312x",
      photo2:
        "http://pix1.agoda.net/hotelimages/54/-1/23d1750eb7af9f4863ea16c1c9b0cafb.jpg?s=312x",
      photo3:
        "http://pix3.agoda.net/hotelimages/54/54/54_16053115400042940736.jpg?s=312x",
      photo4:
        "http://pix1.agoda.net/hotelimages/54/-1/1d6641875edae6bfdb4a46b113aa95cb.jpg?s=312x",
      photo5:
        "http://pix5.agoda.net/hotelimages/54/-1/bb7b19c0413bfb89d67ae49a0d818837.jpg?s=312x",
      overview:
        "The 4-star Haihua Hotel Hangzhou offers comfort and convenience whether you're on business or holiday in Hangzhou. Featuring a complete list of amenities, guests will find their stay at the property a comfortable one. Free Wi-Fi in all rooms, 24-hour security, daily housekeeping, grocery deliveries, 24-hour front desk are there for guest's enjoyment. Comfortable guestrooms ensure a good night's sleep with some rooms featuring facilities such as television LCD/plasma screen, carpeting, clothes rack, linens, locker. Take a break from a long day and make use of fitness center, sauna, indoor pool, massage. Discover all Hangzhou has to offer by making Haihua Hotel Hangzhou your base.",
      rates_from: 74,
      continent_id: 2,
      continent_name: "Asia",
      city_id: 14892,
      country_id: 191,
      number_of_reviews: 1268,
      rating_average: 7.7,
      rates_currency: "USD",
    },
    {
      hotel_id: 59,
      chain_id: 311,
      chain_name: "Tokyu Hotels",
      brand_id: 591,
      brand_name: "Tokyu Inn",
      hotel_name: "Kobe Sannomiya Tokyu REI Hotel",
      hotel_formerly_name: "Kobe Tokyu Inn",
      hotel_translated_name: "Kobe Sannomiya Tokyu REI Hotel",
      addressline1: "6-1-5 Kumoidori, Chuo-ku",
      addressline2: "",
      zipcode: "651-0096",
      city: "Khon Kaen",
      state: "Northern Thailand",
      country: "Thailand",
      countryisocode: "JP",
      star_rating: 3,
      longitude: 135.196655,
      latitude: 34.694649,
      url: "https://www.agoda.com/partners/partnersearch.aspx?hid=59",
      checkin: "3:00 PM",
      checkout: "11:00 AM",
      numberrooms: 235,
      numberfloors: 12,
      yearopened: 1986,
      yearrenovated: 2017,
      photo1:
        "http://pix2.agoda.net/hotelimages/59/59/59_17050315180052767891.jpg?s=312x",
      photo2:
        "http://pix5.agoda.net/hotelimages/59/59/59_17030514080051374227.jpg?s=312x",
      photo3:
        "http://pix5.agoda.net/hotelimages/59/59/59_16101013470047578644.jpg?s=312x",
      photo4:
        "http://pix4.agoda.net/hotelimages/59/59/59_16101013470047578645.jpg?s=312x",
      photo5:
        "http://pix2.agoda.net/hotelimages/59/59/59_16101013470047578646.jpg?s=312x",
      overview:
        "Kobe Sannomiya Tokyu REI Hotel is perfectly located for both business and leisure guests in Kobe. Featuring a complete list of amenities, guests will find their stay at the property a comfortable one. Service-minded staff will welcome and guide you at the Kobe Sannomiya Tokyu REI Hotel. Guestrooms are designed to provide an optimal level of comfort with welcoming decor and some offering convenient amenities like television LCD/plasma screen, complimentary instant coffee, complimentary tea, linens, slippers. The hotel offers various recreational opportunities. Discover all Kobe has to offer by making Kobe Sannomiya Tokyu REI Hotel your base.",
      rates_from: 58,
      continent_id: 2,
      continent_name: "Asia",
      city_id: 5235,
      country_id: 3,
      number_of_reviews: 764,
      rating_average: 8.5,
      rates_currency: "USD",
    },
    {
      hotel_id: 63,
      chain_id: 0,
      chain_name: "No chain",
      brand_id: 0,
      brand_name: "",
      hotel_name: "Suites South Burlington",
      hotel_formerly_name: "",
      hotel_translated_name: "Suites South Burlington",
      addressline1: "1712 Shelburne Rd.",
      addressline2: "",
      zipcode: "5403",
      city: "Samut Sakhon",
      state: "Central Thailand",
      country: "Thailand",
      countryisocode: "US",
      star_rating: 2.5,
      longitude: -73.211479,
      latitude: 44.425246,
      url: "https://www.agoda.com/partners/partnersearch.aspx?hid=63",
      checkin: "3:00 PM",
      checkout: "11:00 AM",
      numberrooms: 84,
      numberfloors: 4,
      yearopened: null,
      yearrenovated: null,
      photo1:
        "http://pix4.agoda.net/hotelimages/63/0/50265bce9db910781a1d262b65988e77.jpg?s=312x",
      photo2:
        "http://pix1.agoda.net/hotelimages/63/63/63_17091411370056344386.jpg?s=312x",
      photo3:
        "http://pix2.agoda.net/hotelimages/63/63/63_17091411370056344352.jpg?s=312x",
      photo4:
        "http://pix5.agoda.net/hotelimages/63/63/63_17091411370056344388.jpg?s=312x",
      photo5:
        "http://pix1.agoda.net/hotelimages/63/63/63_17091411370056344409.jpg?s=312x",
      overview:
        "Comfort Suites South Burlington is conveniently located in the popular South Burlington area. The hotel offers guests a range of services and amenities designed to provide comfort and convenience. Take advantage of the hotel's free Wi-Fi in all rooms, Wi-Fi in public areas, car park, airport transfer, car hire. Guestrooms are fitted with all the amenities you need for a good night's sleep. In some of the rooms, guests can find air conditioning, wake-up service, desk, alarm clock, telephone. Access to the hotel's fishing, spa, water sports (non-motorized) will further enhance your satisfying stay. Discover all South Burlington (VT) has to offer by making Comfort Suites South Burlington your base.",
      rates_from: 118,
      continent_id: 6,
      continent_name: "North America",
      city_id: 17641,
      country_id: 181,
      number_of_reviews: 12,
      rating_average: 8.4,
      rates_currency: "USD",
    },
    {
      hotel_id: 66,
      chain_id: 0,
      chain_name: "No chain",
      brand_id: 0,
      brand_name: "",
      hotel_name:
        "Everbright Convention & Exhibition Centre International Hotel",
      hotel_formerly_name: "Everbright International Hotel",
      hotel_translated_name:
        "Everbright Convention & Exhibition Centre International Hotel",
      addressline1: "66 Caobao Road, Xuhui district",
      addressline2: "",
      zipcode: "",
      city: "Udon",
      state: "Northern Thailand",
      country: "Thailand",
      countryisocode: "CN",
      star_rating: 4,
      longitude: 121.429146,
      latitude: 31.167866,
      url: "https://www.agoda.com/partners/partnersearch.aspx?hid=66",
      checkin: "2:00 PM",
      checkout: "12:00 PM",
      numberrooms: 432,
      numberfloors: 30,
      yearopened: 1999,
      yearrenovated: null,
      photo1:
        "http://pix5.agoda.net/hotelimages/7456302/0/fe20fe078e5b7195789ac57334dc8cba.jpg?s=312x",
      photo2:
        "http://pix2.agoda.net/hotelimages/66/66/66_13103010150017244355.jpg?s=312x",
      photo3:
        "http://pix4.agoda.net/hotelimages/66/66/66_14061212400019807656.jpg?s=312x",
      photo4:
        "http://pix1.agoda.net/hotelimages/66/66/66_14061212400019807657.jpg?s=312x",
      photo5:
        "http://pix3.agoda.net/hotelimages/66/66/66_14061212400019807658.jpg?s=312x",
      overview:
        "Everbright Convention & Exhibition Centre Internat is perfectly located for both business and leisure guests in Shanghai. Both business travelers and tourists can enjoy the hotel's facilities and services. Service-minded staff will welcome and guide you at the Everbright Convention & Exhibition Centre Internat. Designed for comfort, selected guestrooms offer television LCD/plasma screen, internet access – wireless, non smoking rooms, air conditioning, desk to ensure a restful night. Access to the hotel's hot tub, private beach, fitness center, sauna, golf course (on site) will further enhance your satisfying stay. Friendly staff, great facilities and close proximity to all that Shanghai has to offer are three great reasons you should stay at Everbright Convention & Exhibition Centre Internat.",
      rates_from: 166,
      continent_id: 2,
      continent_name: "Asia",
      city_id: 3987,
      country_id: 191,
      number_of_reviews: 211,
      rating_average: 6.4,
      rates_currency: "USD",
    },
    {
      hotel_id: 69,
      chain_id: 14,
      chain_name: "Hilton Worldwide",
      brand_id: 71,
      brand_name: "Hilton Garden Inn",
      hotel_name: "Hilton Garden Inn Pittsburgh University Place",
      hotel_formerly_name: "Wyndham Garden- University Place Hotel",
      hotel_translated_name: "Hilton Garden Inn Pittsburgh University Place",
      addressline1: "3454 Forbes Avenue",
      addressline2: "",
      zipcode: "15213",
      city: "Koh Tao",
      state: "Northern Thailand",
      country: "Thailand",
      countryisocode: "US",
      star_rating: 3,
      longitude: -79.959274,
      latitude: 40.439487,
      url: "https://www.agoda.com/partners/partnersearch.aspx?hid=69",
      checkin: "3:00 PM",
      checkout: "12:00 PM",
      numberrooms: null,
      numberfloors: null,
      yearopened: null,
      yearrenovated: null,
      photo1:
        "http://pix3.agoda.net/hotelimages/69/0/45bf6f3bfdbf04196eabaacdfaae2ff4.jpg?s=312x",
      photo2:
        "http://pix4.agoda.net/hotelimages/69/3271889/2da4a16bb4021f6845cca2067f61e194.jpg?s=312x",
      photo3:
        "http://pix3.agoda.net/hotelimages/69/69/69_17080817270055081893.jpg?s=312x",
      photo4:
        "http://pix1.agoda.net/hotelimages/69/69/69_17080817270055081908.jpg?s=312x",
      photo5:
        "http://pix5.agoda.net/hotelimages/69/69/69_17080817270055081910.jpg?s=312x",
      overview:
        "Stop at Hilton Garden Inn Pittsburgh University Place to discover the wonders of Pittsburgh (PA). The hotel offers a wide range of amenities and perks to ensure you have a great time. 24-hour front desk, facilities for disabled guests, express check-in/check-out, luggage storage, Wi-Fi in public areas are just some of the facilities on offer. All rooms are designed and decorated to make guests feel right at home, and some rooms come with television LCD/plasma screen, air conditioning, heating, desk, alarm clock. The hotel offers various recreational opportunities. A welcoming atmosphere and excellent service are what you can expect during your stay at Hilton Garden Inn Pittsburgh University Place.",
      rates_from: 200,
      continent_id: 6,
      continent_name: "North America",
      city_id: 11488,
      country_id: 181,
      number_of_reviews: 16,
      rating_average: 8.4,
      rates_currency: "USD",
    },
    {
      hotel_id: 71,
      chain_id: 0,
      chain_name: "No chain",
      brand_id: 0,
      brand_name: "",
      hotel_name: "Hotel Apogia Nice",
      hotel_formerly_name: "Apogia Hotel",
      hotel_translated_name: "Hotel Apogia Nice",
      addressline1: "26, Rue Smolett",
      addressline2: "",
      zipcode: "6300",
      city: "Pai",
      state: "Northern Thailand",
      country: "Thailand",
      countryisocode: "FR",
      star_rating: 4,
      longitude: 7.284279,
      latitude: 43.703529,
      url: "https://www.agoda.com/partners/partnersearch.aspx?hid=71",
      checkin: "3:00 PM",
      checkout: "12:00 PM",
      numberrooms: 101,
      numberfloors: 5,
      yearopened: null,
      yearrenovated: null,
      photo1:
        "http://pix4.agoda.net/hotelimages/71/71/71_15112522040038031555.jpg?s=312x",
      photo2:
        "http://pix2.agoda.net/hotelimages/71/71/71_14110516150023200624.jpg?s=312x",
      photo3:
        "http://pix1.agoda.net/hotelimages/71/71/71_14110514240023196635.jpg?s=312x",
      photo4:
        "http://pix3.agoda.net/hotelimages/71/71/71_14110514240023196639.jpg?s=312x",
      photo5:
        "http://pix5.agoda.net/hotelimages/71/71/71_14110514240023196643.jpg?s=312x",
      overview:
        "Hotel Apogia Nice is conveniently located in the popular Nice City Center area. Offering a variety of facilities and services, the hotel provides all you need for a good night's sleep. Facilities like free Wi-Fi in all rooms, daily housekeeping, wheelchair accessible, 24-hour front desk, facilities for disabled guests are readily available for you to enjoy. Designed for comfort, selected guestrooms offer television LCD/plasma screen, internet access – wireless, internet access – wireless (complimentary), non smoking rooms, air conditioning to ensure a restful night. The hotel offers various recreational opportunities. Hotel Apogia Nice is an excellent choice from which to explore Nice or to simply relax and rejuvenate.",
      rates_from: 61,
      continent_id: 4,
      continent_name: "Europe",
      city_id: 5277,
      country_id: 153,
      number_of_reviews: 121,
      rating_average: 7.6,
      rates_currency: "USD",
    },
    {
      hotel_id: 75,
      chain_id: 74,
      chain_name: "Caesars Entertainment Corporation",
      brand_id: 1085,
      brand_name: "Caesars Entertainment Corporation",
      hotel_name: "Paris Las Vegas",
      hotel_formerly_name: "",
      hotel_translated_name: "Paris Las Vegas",
      addressline1: "3655 Las Vegas Boulevard South",
      addressline2: "",
      zipcode: "89109",
      city: "Buri",
      state: "Central Thailand",
      country: "Thailand",
      countryisocode: "US",
      star_rating: 4,
      longitude: -115.17086,
      latitude: 36.112019,
      url: "https://www.agoda.com/partners/partnersearch.aspx?hid=75",
      checkin: "4:00 PM",
      checkout: "11:00 AM",
      numberrooms: 2916,
      numberfloors: 34,
      yearopened: 1999,
      yearrenovated: null,
      photo1:
        "http://pix2.agoda.net/hotelimages/75/-1/450838815fb602d9fe58bba500a04a84.jpg?s=312x",
      photo2:
        "http://pix1.agoda.net/hotelimages/75/75/75_16102701360048160956.jpg?s=312x",
      photo3:
        "http://pix1.agoda.net/hotelimages/75/75/75_14041902380019131757.jpg?s=312x",
      photo4:
        "http://pix3.agoda.net/hotelimages/75/75/75_16063004510044267771.jpg?s=312x",
      photo5:
        "http://pix1.agoda.net/hotelimages/75/75/75_16063004510044267772.jpg?s=312x",
      overview:
        "Paris Las Vegas Hotel is perfectly located for both business and leisure guests in Las Vegas (NV). The hotel offers a wide range of amenities and perks to ensure you have a great time. Service-minded staff will welcome and guide you at the Paris Las Vegas Hotel. Television LCD/plasma screen, carpeting, linens, mirror, towels can be found in selected guestrooms. The hotel's peaceful atmosphere extends to its recreational facilities which include fitness center, sauna, outdoor pool, spa, steamroom. Paris Las Vegas Hotel combines warm hospitality with a lovely ambiance to make your stay in Las Vegas (NV) unforgettable.",
      rates_from: 129,
      continent_id: 6,
      continent_name: "North America",
      city_id: 17072,
      country_id: 181,
      number_of_reviews: 1710,
      rating_average: 8.1,
      rates_currency: "USD",
    },
    {
      hotel_id: 78,
      chain_id: 161,
      chain_name: "Hoteles Catalonia",
      brand_id: 340,
      brand_name: "Hoteles Catalonia",
      hotel_name: "Catalonia Brussels Hotel",
      hotel_formerly_name: "Hotel Catalonia Forum",
      hotel_translated_name: "Catalonia Brussels Hotel",
      addressline1: "Avenue du Haut-Pont, 2 Hoge Bruglaan",
      addressline2: "",
      zipcode: "B1060",
      city: "Mae Hong Son",
      state: "Central Thailand",
      country: "Thailand",
      countryisocode: "BE",
      star_rating: 3,
      longitude: 4.35322,
      latitude: 50.820938,
      url: "https://www.agoda.com/partners/partnersearch.aspx?hid=78",
      checkin: "3:00 PM",
      checkout: "12:00 PM",
      numberrooms: 80,
      numberfloors: null,
      yearopened: 1978,
      yearrenovated: 2004,
      photo1:
        "http://pix2.agoda.net/hotelimages/78/0/c0c8e0157b466534215921d295e02974.jpg?s=312x",
      photo2:
        "http://pix4.agoda.net/hotelimages/78/78/78_17110906000058958908.jpg?s=312x",
      photo3:
        "http://pix1.agoda.net/hotelimages/78/78/78_16051514190042342598.jpg?s=312x",
      photo4:
        "http://pix2.agoda.net/hotelimages/78/78/78_16051514190042342599.jpg?s=312x",
      photo5:
        "http://pix4.agoda.net/hotelimages/78/78/78_16051514190042342614.jpg?s=312x",
      overview:
        "Ideally located in the prime touristic area of Elsene / Ixelles, Hotel HC Brussels promises a relaxing and wonderful visit. The hotel offers a high standard of service and amenities to suit the individual needs of all travelers. Free Wi-Fi in all rooms, facilities for disabled guests, Wi-Fi in public areas, car park, room service are there for guest's enjoyment. Comfortable guestrooms ensure a good night's sleep with some rooms featuring facilities such as internet access – wireless, air conditioning, heating, wake-up service, desk. The hotel offers various recreational opportunities. No matter what your reasons are for visiting Brussels, Hotel HC Brussels will make you feel instantly at home.",
      rates_from: 80,
      continent_id: 4,
      continent_name: "Europe",
      city_id: 15904,
      country_id: 118,
      number_of_reviews: 35,
      rating_average: 8.1,
      rates_currency: "USD",
    }
  ];

